-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'MANAGER', 'USER');

-- CreateEnum
CREATE TYPE "TipoPermissao" AS ENUM ('CRIAR_ORCAMENTO', 'EDITAR_ORCAMENTO', 'EXCLUIR_ORCAMENTO', 'APROVAR_ORCAMENTO', 'VISUALIZAR_ORCAMENTO', 'CRIAR_CLIENTE', 'EDITAR_CLIENTE', 'EXCLUIR_CLIENTE', 'VISUALIZAR_CLIENTE', 'CRIAR_PRODUTO', 'EDITAR_PRODUTO', 'EXCLUIR_PRODUTO', 'VISUALIZAR_PRODUTO', 'CRIAR_SERVICO', 'EDITAR_SERVICO', 'EXCLUIR_SERVICO', 'VISUALIZAR_SERVICO', 'GERENCIAR_USUARIOS');

-- AlterTable
ALTER TABLE "Usuarios" ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lastLogin" TIMESTAMP(3),
ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER';

-- CreateTable
CREATE TABLE "Permissoes" (
    "id" SERIAL NOT NULL,
    "tipo" "TipoPermissao" NOT NULL,
    "usuarioId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Permissoes_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Permissoes_usuarioId_tipo_key" ON "Permissoes"("usuarioId", "tipo");

-- AddForeignKey
ALTER TABLE "Permissoes" ADD CONSTRAINT "Permissoes_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES "Usuarios"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
